version: '2'

services:
  phpfpm:
    image: 'bitnami/php-fpm:8.1.3'
    container_name: phpfpm-container
    volumes:
      - './app:/app'

  nginx:
    image: 'bitnami/nginx:latest'
    container_name: nginx-container
    depends_on:
      - phpfpm
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './server_block.conf:/opt/bitnami/nginx/conf/server_blocks/server_block.conf:ro'
      - './app:/app'
